# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-10 13:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='date',
            field=models.DateField(auto_now=True, default=datetime.datetime(2017, 11, 10, 13, 28, 10, 930849, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
