# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-23 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20171113_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', verbose_name=''),
            preserve_default=False,
        ),
    ]
