# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-03 11:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20171123_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date',
            field=models.DateField(auto_now=True, default=datetime.datetime(2017, 12, 3, 11, 38, 25, 673209, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
