# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-03 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_category_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date',
            field=models.DateField(),
        ),
    ]
