# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-08 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlvalidator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmldocument',
            name='decree_point',
            field=models.CharField(choices=[('12_1_2', '12_1_2'), ('12_1_3', '12_1_3')], default='12_1_2', max_length=30),
        ),
    ]
